apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: traceassist
type: Opaque
stringData:
  # ← Your existing OpenAI key
  OPENAI_API_KEY: "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"
  # ← Your existing PAT_TOKEN (if still needed by your app)
  PAT_TOKEN: "-----------------------------------------"

  # ─── New Jira credentials ─────────────────────────────────────────────────
  jira_user_email: "harshitjindal02@gmail.com"        # ← the email you log into Jira Cloud with
  jira_api_token: "ATATT3xFfGF0xilvKcvVSqdSrjmgSSH63mIkIlzdgXM6smkxF0JhqAnLaWPpYGky5SubVAYA7QVYlwMPjKdi4V3VIq5igikRDHIGXY36cDftrEc1fxnwYCUQqbrjftpdOHlU2v3OKMfOXXLnLE4niSilHiYvk0E8rMxRYXgnsVZoloH0GO_ClEA=02BDA234"   # ← the API token you created
