apiVersion: apps/v1
kind: Deployment
metadata:
  name: traceassist-backend
  namespace: traceassist
spec:
  replicas: 1
  selector:
    matchLabels:
      app: traceassist-backend
  template:
    metadata:
      labels:
        app: traceassist-backend
    spec:
      serviceAccountName: traceassist-sa
      volumes:
        - name: dockersock
          hostPath:
            path: /var/run/docker.sock
            type: Socket
      containers:
        - name: backend
          image: traceassist-backend:latest
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: dockersock
              mountPath: /var/run/docker.sock
          ports:
            - containerPort: 8000
          env:
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: OPENAI_API_KEY
            - name: PAT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: PAT_TOKEN

            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "https://ingest.in.signoz.cloud:4317"
            - name: OTEL_EXPORTER_OTLP_HEADERS
              value: "Authorization=Bearer e9bfcba0-a5a1-4d45-b2d5-38d332625ac8"

            - name: LOKI_ENDPOINT
              value: "http://loki.traceassist.svc.cluster.local:3100"
            - name: JIRA_BASE_URL
              value: "https://harshitjindal02.atlassian.net"
            - name: JIRA_PROJECT_KEY
              value: "TRACE"
            - name: JIRA_USER_EMAIL
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: jira_user_email
            - name: JIRA_API_TOKEN
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: jira_api_token
